### PR TITLE
(1/2) Properly support camera orientation (V.2)

### LINKED ISSUE #370: new FP2 camera: Pictures and Videos captured with the front camera will be rotated by 180 degrees
New camera module on FP2: Pictures and Videos captured with the front camera will be rotated by 180 degrees

### PR DESCRIPTION
**Pull request by peat-psuwit**
This PR make the plugin handles the orientation of the device within the plugin itself, removing the need for applications to deal with it, and complying with what other plugins do. This PR also correct the reported camera orientation by inverting the value given from Android as it has a different meaning.

This partially fixes ubports/ubuntu-touch#370 and superseded #1.

### CODE REVIEW

**Comment by peat-psuwit** [comment]
A test from @cibersheep indicates that orientation override doesn't work. Will need some time to fix this.

**Comment by peat-psuwit** [comment]
The problem is fixed. PR updated.

**Review by UniversalSuperBox — APPROVED** [review]
This tests fine on the FP2 with old camera module, Oneplus One, Nexus 5, and Nexus 7. We've also seen tests from the FP2 with new camera module and this actually fixes the problem. I think we can get this into devel (Assuming https://gitlab.com/ubports/apps/camera-app/merge_requests/122 is merged in tandem)

**Comment by Flohack74** [comment]
But can we merge the change to camera-app which will update on all stable channel devices as well? Wont it affect that, and we need to wait with this app update after the OTA?

**Comment by peat-psuwit** [comment]
@UniversalSuperBox suggested me to [bump the framework version](https://gitlab.com/ubports/apps/camera-app/merge_requests/122/diffs#50fefa7e46dfe6575ab9bd8ffbea0506f301fa0e_3_3). So, it won't be installable on stable channel device. Not sure how it works in OpenStore though. Also, maybe the preinstalled click should be upgraded as well?

**Comment by Flohack74** [comment]
I see. I will talk with him.

**Comment by cibersheep** [comment]
If you install the camera app without the updated framwork, Camera app desappears from the App Scope :)

**Comment by UniversalSuperBox** [comment]
The OpenStore won't offer an incompatible app upgrade. The old camera app works with the new qtubuntu-camera.

**Pull request merged**
